### ISSUE TITLE
Grok Integration?

### ISSUE THREAD

**Issue by NathanielComeau** [browser-use/browser-use#127]
Has anybody tried to use this with Groq? I'm getting an `invalid_api_key` error. Please close this issue if it's something stupid I'm doing, and Groq should work fine. Here's a script for reference.

```
from langchain_groq import ChatGroq
#from langchain_openai import ChatOpenAI
from browser_use import Agent
import asyncio

async def main():
    agent = Agent(
        task="Are there cheap flights from ... to ...?",
        llm=ChatGroq(model="llama3-8b-8192"),
    )
    result = await agent.run()
    print(result)

asyncio.run(main())
```
Thanks.

**Comment by sbhavani** [comment]
I just checked and it works for me. Try putting the env variable before the script when you run it (e.g. GROQ_API_KEY=XXX python test.py)

Also your issue title mentions 'Grok', check if you're referring to the model from xAI or groq.com provider

**Comment by NathanielComeau** [comment]
Okay, thank you very much for checking it @sbhavani .

Aha! Yes, I was looking to try it out with 'Grok', so that explains why the xAI API key wasn't working.

Thanks very much.

**Comment by akc2267** [comment]
just a note, I got this (kinda) working with Groq with the following. It doesn't complete the full flow but it does open chromium:

```
from langchain_groq import ChatGroq
#from langchain_openai import ChatOpenAI
from browser_use import Agent
import asyncio

async def main():
    agent = Agent(
        task="Are there cheap flights from AUS to LAX?",
        llm=ChatGroq(model="llama-3.3-70b-versatile"),
    )
    result = await agent.run()
    print(result)

if __name__ == "__main__":
    asyncio.run(main())
```

In terminal, I run:
`GROQ_API_KEY=api_key_here python groqtest.py`

Note, don't call your python script "groq.py" or you'll end up in a circular dependency error

**Comment by akc2267** [comment]
looks like it fails because Groq models are not multi-modal
